### ISSUE TITLE
Visual grouping of sign up input fields leaves room for confusion

### ISSUE THREAD

**Issue by polarbirke** [5t3ph/a11y-fails#4]
It would probably be beneficial to increase the vertical gaps between label/input groups. Currently, the visual hierarchy leaves room for confusion whether labels are preceding their inputs or sitting directly underneath them.

<img width="372" alt="Bildschirmfoto 2020-07-25 um 22 53 42" src="https://user-images.githubusercontent.com/3763421/88466195-2e140100-ceca-11ea-82bd-bed56eec010a.png">

The [Law of Proximity](https://lawsofux.com/law-of-proximity) states that "Objects that are near, or proximate to each other, tend to be grouped together." Adding a margin-top, e.g. to labels following an input, would fix that.

**Comment by 5t3ph** [comment]
You _could_ argue that's an accessibility-related fix as well ;) Is that the way you intend for this issue, to be rolled into the "fix" PR?

**Comment by 5t3ph** [comment]
Realized ss was from the "fix" version, so I have made an adjustment to address this. Thanks!
